name: Create packages

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install build dependencies
        run: sudo apt-get install gettext

      - name: Build packages
        run:  |
            make && cd kodi && make && cd ..
            mkdir dist
            mv ttml2ssa-*.zip dist
            mv kodi/script.module.ttml2ssa-*.zip dist

      - name: Get packages names
        run: |
            cd dist
            PACKAGELINUX=`ls ttml2ssa-*.zip`
            PACKAGEKODILEIA=`ls script.module.ttml2ssa-*-leia.zip`
            PACKAGEKODIMATRIX=`ls script.module.ttml2ssa-*-matrix.zip`
            echo "PACKAGELINUX=$PACKAGELINUX" >> $GITHUB_ENV
            echo "PACKAGEKODILEIA=$PACKAGEKODILEIA" >> $GITHUB_ENV
            echo "PACKAGEKODIMATRIX=$PACKAGEKODIMATRIX" >> $GITHUB_ENV
            
      - name: Upload linux package
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PACKAGELINUX }}
          path: dist/${{ env.PACKAGELINUX }}
       
      - name: Upload package kodi leia
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PACKAGEKODILEIA }}
          path: dist/${{ env.PACKAGEKODILEIA }}
       
      - name: Upload package kodi matrix
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PACKAGEKODIMATRIX }}
          path: dist/${{ env.PACKAGEKODIMATRIX }}

      - name: Upload packages to release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
